[general]
import = [
  "~/.config/alacritty/keybindings.toml",
  #"~/.config/alacritty/solarized_dark.toml",
  "~/.config/alacritty/themes/themes/selenized_light.toml",
]
live_config_reload = true

[cursor.style]
blinking = "On"
shape = "Block"

[font]
size = 13

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[scrolling]
history = 50000

[selection]
save_to_clipboard = true

# [mouse]
# hide_when_typing = true

[terminal.shell]
program = "/bin/zsh"
args = ["--login"]
# args = ["--login", "-c", "/opt/homebrew/bin/tmux new-session -A -D -s main"]

#[[mouse.bindings]]
#mouse = "Right"
#action = "PasteSelection"

[window]
# decorations = "Buttonless"  # More native macOS look
opacity = 1.0
dynamic_padding = true
dynamic_title = true
startup_mode = "Windowed"
# option_as_alt = "Both"  # Better Alt key handling

# [window.padding]
# x = 3
# y = 3

# https://github.com/helderberto/dotfiles/blob/main/alacritty/.alacritty.toml
# Improve terminal response
[env]
TERM = "xterm-256color"
COLORTERM = "truecolor" # Enable true color support
EDITOR = "nvim"         # Set default editor


[debug]
# Improve performance
render_timer = false
persistent_logging = false
log_level = "Warn"
# log_level = "Debug"
print_events = false


# [colors.primary]
# background = "#0c2732"
# foreground = "#b1cbcd"
