[manager]
ratio          = [ 1, 4, 3 ]
sort_by        = "alphabetical"
sort_sensitive = false
sort_reverse   = false
sort_dir_first = true
sort_translit  = false
linemode       = "none"
show_hidden    = false
show_symlink   = true
scrolloff      = 5
mouse_events   = [ "click", "scroll" ]
title_format   = "Yazi: {cwd}"

[preview]
tab_size        = 2
max_width       = 600
max_height      = 900
cache_dir       = ""
image_filter    = "triangle"
image_quality   = 75
sixel_fraction  = 15
ueberzug_scale  = 1

[opener]
edit = [
	{ run = '$EDITOR "$1"', desc = "$EDITOR", block = true, for = "unix" },
	{ run = 'code "$@"', orphan = true, desc = "VSCode", for = "macos" },
    { run = 'neovide "$@"', block = true, orphan = true, desc = "Neovide", for = "macos" },
]
open = [
	{ run = 'open "$1"', desc = "Open", for = "macos" },
	{ run = 'xdg-open "$1"', desc = "Open", for = "linux" },
]
reveal = [
	{ run = 'open -R "$1"', desc = "Reveal", for = "macos" },
	{ run = 'xdg-open "$(dirname "$1")"', desc = "Reveal", for = "linux" },
]
extract = [
	{ run = 'unar "$1"', desc = "Extract here" },
]
play = [
	{ run = 'mpv "$1"', desc = "Play with mpv" },
	{ run = 'vlc "$1"', desc = "Play with VLC" },
]

[open]
rules = [
	{ name = "*/", use = [ "edit", "open", "reveal" ] },

	{ mime = "text/*", use = [ "edit", "reveal" ] },
	{ mime = "image/*", use = [ "open", "reveal" ] },
	{ mime = "video/*", use = [ "play", "reveal" ] },
	{ mime = "audio/*", use = [ "play", "reveal" ] },
	{ mime = "inode/x-empty", use = [ "edit", "reveal" ] },

	{ mime = "application/json", use = [ "edit", "reveal" ] },
	{ mime = "*/javascript", use = [ "edit", "reveal" ] },

	{ mime = "application/zip", use = [ "extract", "reveal" ] },
	{ mime = "application/gzip", use = [ "extract", "reveal" ] },
	{ mime = "application/x-tar", use = [ "extract", "reveal" ] },
	{ mime = "application/x-bzip2", use = [ "extract", "reveal" ] },
	{ mime = "application/x-7z-compressed", use = [ "extract", "reveal" ] },
	{ mime = "application/x-rar", use = [ "extract", "reveal" ] },
	{ mime = "application/xz", use = [ "extract", "reveal" ] },
]

[tasks]
micro_workers    = 10
macro_workers    = 25
bizarre_retry    = 5
image_alloc      = 536870912  # 512MB
image_bound      = [ 0, 0 ]
suppress_preload = false

[plugin]

[input]
cursor_blink = false

[select]
open_title  = "Open with:"
open_origin = "bottom-left"
open_offset = [ 0, 1 ]

[which]
sort_by        = "none"
sort_sensitive = false
sort_reverse   = false

[log]
enabled = false

